version: '3'

services:
  # Postgress database
  pgdb:
    image: postgres:17
    container_name: database
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  # Flask App.
  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    environment:
      DATABASE_URI: "postgresql+psycopg2://postgres:${DB_PASSWORD}@pgdb/postgres"
      MAIL_SERVER: "smtp.googlemail.com"
      MAIL_PORT: 587
      MAIL_USE_TLS: 1
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      RAZORPAY_CLIENT_ID: ${RAZORPAY_CLIENT_ID}
      RAZORPAY_CLIENT_SECRET: ${RAZORPAY_CLIENT_SECRET}
      JWT_SECRET: ${JWT_SECRET}
      SECRET_KEY: ${SECRET_KEY}
    depends_on:
      - pgdb
    restart: unless-stopped
  
  # Nginx container.
  nginx:
    container_name: nginx
    restart: unless-stopped
    image: nginx:1.27
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - certbot

  # Certbot container.
  certbot:
    image: certbot/certbot:v2.11.0
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: certonly --webroot -w /var/www/certbot --force-renewal --email gpt.sahaj28@gmail.com -d pokemarket.in --agree-tos
    depends_on:
      - server

volumes:
  pgdata:
