"""Added Genration column in Pokemon Table

Revision ID: 0ac22aa1aacb
Revises: 9bcabe3fbb43
Create Date: 2024-09-05 03:52:34.094646

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ac22aa1aacb'
down_revision = '9bcabe3fbb43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pokemon', schema=None) as batch_op:
        batch_op.add_column(sa.Column('generation', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pokemon', schema=None) as batch_op:
        batch_op.drop_column('generation')

    # ### end Alembic commands ###
