"""Added quantity column in pokemoncart table.

Revision ID: 4bbfe595373f
Revises: 6a29b9e3607a
Create Date: 2024-10-02 13:59:13.094454

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4bbfe595373f'
down_revision = '6a29b9e3607a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pokemons_carts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pokemons_carts', schema=None) as batch_op:
        batch_op.drop_column('quantity')

    # ### end Alembic commands ###
